# -*- coding: utf-8 -*-
"""code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DaHkwY2TyIgnskT-9ClAIxRQgxoRFUi1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import requests
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from xgboost import XGBClassifier, XGBRegressor
from sklearn.metrics import accuracy_score, r2_score
import warnings
warnings.filterwarnings("ignore")

# Load Dataset
df = pd.read_csv("/content/TamilNadu_Agriculture_Dataset_Realistic_Expanded (1).csv")

df.head()

df.tail()

df.info()
df.describe()

# Convert Date to datetime format
df['Date(%y-%m-%d)'] = pd.to_datetime(df['Date(%y-%m-%d)'])
df['Month'] = df['Date(%y-%m-%d)'].dt.month
df['DayOfYear'] = df['Date(%y-%m-%d)'].dt.dayofyear

# Encode District and Crop Name
district_encoder = LabelEncoder()
df['District'] = district_encoder.fit_transform(df['District'])

crop_encoder = LabelEncoder()
df['Crop'] = crop_encoder.fit_transform(df['Crop'])

# 1. Feature Distribution
features = ['N(kg/ha)', 'P(kg/ha)', 'K(kg/ha)', 'pH', 'Temperature(°C)', 'Humidity(%)', 'Rainfall(mm)', 'Yield(kg/ha)'] # Define features list

plt.figure(figsize=(12, 6))
df[features].hist(bins=30, figsize=(12, 8), layout=(3, 4), color='steelblue', edgecolor='black')
plt.suptitle("Feature Distributions", fontsize=14)
plt.show()

# 2. Correlation Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(df[features].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

# 3. Crop Distribution
plt.figure(figsize=(10, 5))
sns.countplot(data=df, y='Crop', order=df['Crop'].value_counts().index, palette="viridis")
plt.title("Crop Distribution in Dataset")
plt.xlabel("Count")
plt.ylabel("Crop Type")
plt.show()

# 4. Actual vs Predicted for Crop Yield (Regression)
plt.figure(figsize=(8, 5))
plt.scatter(y_yield_test, y_yield_pred, alpha=0.5, color="red", edgecolors="black")
plt.xlabel("Actual Crop Yield")
plt.ylabel("Predicted Crop Yield")
plt.title("Actual vs Predicted Crop Yield")
plt.show()

# Set style
sns.set_style("whitegrid")

# *1️⃣ Accuracy Bar Chart for Crop Recommendation*
plt.figure(figsize=(6, 4))
plt.bar(["Crop Recommendation"], [crop_acc * 100], color='royalblue')
plt.ylabel("Accuracy (%)")
plt.title("Crop Recommendation Model Accuracy")
plt.ylim(0, 100)
plt.text(0, crop_acc * 100 + 2, f"{crop_acc * 100:.2f}%", ha='center', fontsize=12)
plt.show()

# *2️⃣ Scatter Plot for Crop Yield Prediction*
plt.figure(figsize=(6, 4))
sns.scatterplot(x=y_yield_test, y=y_yield_pred, color='green')
plt.plot(y_yield_test, y_yield_test, 'r', linestyle='--')  # Ideal Prediction Line
plt.xlabel("Actual Crop Yield")
plt.ylabel("Predicted Crop Yield")
plt.title(f"Crop Yield Prediction (R² = {yield_r2:.2f})")
plt.show()

# *3️⃣ Scatter Plot for Market Price Prediction*
plt.figure(figsize=(6, 4))
sns.scatterplot(x=y_price_test, y=y_price_pred, color='orange')
plt.plot(y_price_test, y_price_test, 'r', linestyle='--')  # Ideal Prediction Line
plt.xlabel("Actual Market Price")
plt.ylabel("Predicted Market Price")
plt.title(f"Market Price Prediction (R² = {price_r2:.2f})")
plt.show()

# *Outlier Removal*
for col in ['N(kg/ha)', 'P(kg/ha)', 'K(kg/ha)', 'pH', 'Temperature(°C)', 'Humidity(%)', 'Rainfall(mm)', 'Yield(kg/ha)', 'Total_Market_Price(INR/ha)']:
    df = df[df[col].between(df[col].quantile(0.01), df[col].quantile(0.99))]

# Define Features and Targets (with pH added)
X_crop = df[['N(kg/ha)', 'P(kg/ha)', 'K(kg/ha)', 'pH', 'Temperature(°C)', 'Humidity(%)', 'Rainfall(mm)']]
y_crop = df['Crop']

X_yield = df[['Crop', 'N(kg/ha)', 'P(kg/ha)', 'K(kg/ha)', 'pH', 'Temperature(°C)', 'Humidity(%)', 'Rainfall(mm)']]
y_yield = df['Yield(kg/ha)']

X_price = df[['Crop', 'Yield(kg/ha)', 'District', 'Month', 'DayOfYear']]
y_price = df['Total_Market_Price(INR/ha)']

# Train-Test Split
X_crop_train, X_crop_test, y_crop_train, y_crop_test = train_test_split(X_crop, y_crop, test_size=0.2, random_state=42)
X_yield_train, X_yield_test, y_yield_train, y_yield_test = train_test_split(X_yield, y_yield, test_size=0.2, random_state=42)
X_price_train, X_price_test, y_price_train, y_price_test = train_test_split(X_price, y_price, test_size=0.2, random_state=42)

# *Feature Scaling*
scaler_crop = StandardScaler()
X_crop_train_scaled = scaler_crop.fit_transform(X_crop_train)
X_crop_test_scaled = scaler_crop.transform(X_crop_test)

scaler_yield = StandardScaler()
X_yield_train_scaled = scaler_yield.fit_transform(X_yield_train)
X_yield_test_scaled = scaler_yield.transform(X_yield_test)

scaler_price = StandardScaler()
X_price_train_scaled = scaler_price.fit_transform(X_price_train)
X_price_test_scaled = scaler_price.transform(X_price_test)

# *Hyperparameter Tuning for XGBoost*
param_grid = {
    'n_estimators': [50, 100, 200, 300, 500],
    'max_depth': [3, 5, 10, 15],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
}

# *Train Models with XGBoost*
crop_model = GridSearchCV(XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'), param_grid, cv=3)
crop_model.fit(X_crop_train_scaled, y_crop_train)

yield_model = GridSearchCV(XGBRegressor(), param_grid, cv=3)
yield_model.fit(X_yield_train_scaled, y_yield_train)

price_model = GridSearchCV(XGBRegressor(), param_grid, cv=3)
price_model.fit(X_price_train_scaled, y_price_train)

# *Save Models & Encoders*
joblib.dump(crop_model.best_estimator_, "crop_model.pkl")
joblib.dump(yield_model.best_estimator_, "yield_model.pkl")
joblib.dump(price_model.best_estimator_, "price_model.pkl")
joblib.dump(district_encoder, "district_encoder.pkl")
joblib.dump(crop_encoder, "crop_encoder.pkl")
joblib.dump(scaler_crop, "scaler_crop.pkl")
joblib.dump(scaler_yield, "scaler_yield.pkl")
joblib.dump(scaler_price, "scaler_price.pkl")

# Predictions & Evaluation
y_crop_pred = crop_model.best_estimator_.predict(X_crop_test_scaled)
y_yield_pred = yield_model.predict(X_yield_test_scaled) # Changed this line
y_price_pred = price_model.predict(X_price_test_scaled) # Changed this line

crop_acc = accuracy_score(y_crop_test, y_crop_pred)
yield_r2 = r2_score(y_yield_test, y_yield_pred)
price_r2 = r2_score(y_price_test, y_price_pred)

print(f"✅ Crop Recommendation Accuracy: {crop_acc * 100:.2f}%")
print(f"✅ Crop Yield R² Score: {yield_r2:.2f}")
print(f"✅ Market Price R² Score: {price_r2:.2f}")

# Function to fetch weather data from API
def fetch_weather_data(district):
    API_KEY = "b31c8ba31d3c4e4584691624251003"  # Replace with your WeatherAPI key
    url = f"http://api.weatherapi.com/v1/current.json?key={API_KEY}&q={district}&aqi=no"

    try:
        response = requests.get(url)
        data = response.json()
        return data['current']['temp_c'], data['current']['humidity'], 50  # Dummy Rainfall (API doesn't provide)
    except:
        return None  # If API fails, user must enter manually

def get_user_input():
    while True:
        try:
            # Get district input first
            district = input("Enter District Name for api: ")  # Added this line to get district input
            weather_data = fetch_weather_data(district)

            if weather_data:
                temperature, humidity, rainfall = weather_data
                print(f"Fetched from API: Temp={temperature}°C, Humidity={humidity}%, Rainfall={rainfall}mm")
                print("Api Fetched weather data successfully")
            else:
                print("⚠️ Failed to fetch weather data from API. Please enter manually.")
                temperature = float(input("Enter Temperature (°C): "))
                humidity = float(input("Enter Humidity (%): "))
                rainfall = float(input("Enter Rainfall (mm): "))

            print("🌱Enter Your Inputs🌾🌱")
            N = float(input("Enter Nitrogen (N) level: "))
            P = float(input("Enter Phosphorus (P) level: "))
            K = float(input("Enter Potassium (K) level: "))
            pH = float(input("Enter Soil pH value: "))
            # Temperature = float(input("Enter Temperature: ")) # This line was commented out - causing the issue
            # Humidity = float(input("Enter Humidity: "))     # This line was commented out - causing the issue
            # Rainfall = float(input("Enter Rainfall: "))     # This line was commented out - causing the issue

            District = input("Enter District name: ")  # This is for the prediction, might be redundant if same as API district
            Date = input("Enter Date (YYYY-MM-DD): ")
            # Validate Date Format
            try:
             Date = pd.to_datetime(Date, format="%Y-%m-%d")
            except ValueError:
             print("⚠️ Invalid date format! Please enter in YYYY-MM-DD format.")
             continue

            Month = Date.month
            DayOfYear = Date.dayofyear

            # Load Encoder
            district_encoder = joblib.load("district_encoder.pkl")

            # Validate District Input
            if District in district_encoder.classes_:
             District_encoded = district_encoder.transform([District])[0]
            else:
             print("⚠️ Invalid District! Please enter a valid district name from the dataset.")
             continue  # Ask for input again if district is invalid

            # Use the values obtained from fetch_weather_data or user input
            return [[N, P, K, pH, temperature, humidity, rainfall]], District_encoded, Month, DayOfYear # Changed this line

        except ValueError:
            print("⚠️ Invalid input! Please enter numerical values for N, P, K, pH, Temperature, Humidity, and Rainfall.")

# Load Models
crop_model = joblib.load("crop_model.pkl")
yield_model = joblib.load("yield_model.pkl")
price_model = joblib.load("price_model.pkl")
crop_encoder = joblib.load("crop_encoder.pkl")
scaler_crop = joblib.load("scaler_crop.pkl")
scaler_yield = joblib.load("scaler_yield.pkl")
scaler_price = joblib.load("scaler_price.pkl")

# Get User Input
user_data, district_encoded, month, day_of_year = get_user_input()

# Predict Crop
user_data_scaled = scaler_crop.transform(user_data)
predicted_crop_encoded = crop_model.predict(user_data_scaled)[0]
predicted_crop = crop_encoder.inverse_transform([predicted_crop_encoded])[0]

# Predict Yield
user_yield_data = [[predicted_crop_encoded] + user_data[0]]
user_yield_data_scaled = scaler_yield.transform(user_yield_data)
predicted_yield = yield_model.predict(user_yield_data_scaled)[0]

# Predict Market Price
user_price_data = [[predicted_crop_encoded, predicted_yield, district_encoded, month, day_of_year]]
user_price_data_scaled = scaler_price.transform(user_price_data)
predicted_price = price_model.predict(user_price_data_scaled)[0]

print("\n🌱*Prediction Results*🌱")
print(f"🌾 *Recommended Crop:* {predicted_crop}")
print(f"🌱 *Predicted Crop Yield:* {predicted_yield:.2f} kg/ha")
print(f"💰 *Predicted Market Price:* ₹{predicted_price:.2f} INR/ha")  