# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZbrqhc6f-W-TDC0eX4ltsb6zBSQ4GWd
"""


import streamlit as st
import joblib
import base64
import matplotlib
import requests
from streamlit_lottie import st_lottie  
import pandas as pd
import numpy as np
import sqlite3
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")

# --- Functions ---
def get_base64(file_path):
    with open(file_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode()

def load_lottieurl(url):
    return requests.get(url).json()

# --- Background Image (Optional) ---
base64_img = get_base64("smart farming2.jpeg")
st.markdown(f"""
<style>
[data-testid="stAppViewContainer"] {{
    background-image: url("data:image/jpg;base64,{base64_img}");
    background-size: cover;
    background-position: center;
    background-attachment: fixed;
}}
</style>
""", unsafe_allow_html=True)

# --- Custom Styling (Fonts, Layout Tweaks, etc.) ---
st.markdown("""
<style>
body {
    font-family: 'Segoe UI', sans-serif;
}
</style>
""", unsafe_allow_html=True)

# --- Sidebar / Navigation ---
page = st.sidebar.selectbox("Navigate", ["Home", "Dashboard", "About","Agriculture News"])

# --- Page Logic ---
if page == "Home":
    st.title("🌾 Smart Farming Dashboard")
    st.write("Welcome to your smart farming assistant!")

elif page == "Dashboard":
    st.header("📊 Farm Data")
    
elif page == "About":
    st.info("Made with ❤️ using Streamlit")

# --- Optional Lottie Animation ---
lottie_url = "https://assets6.lottiefiles.com/packages/lf20_puciaact.json"
animation = load_lottieurl(lottie_url)
st_lottie(animation, height=300)


# --- CUSTOM CSS STYLING ---
st.markdown(
    """
    <style>
    /* Apply background image to the main Streamlit app container */
    .stApp {
        background: url('https://source.unsplash.com/1600x900/?smart-farming,technology') no-repeat center center fixed;
        background-size: cover;
    }

    /* Add styling to the main content box */
    .main {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 30px;
        border-radius: 12px;
        box-shadow: 5px 5px 20px rgba(0, 0, 0, 0.2);
    }
    

    /* Button styling */
    .stButton>button {
        background-color: green !important;
        color: white !important;
        font-size: 20px !important;
        font-weight: bold !important;
        border-radius: 10px !important;
        padding: 12px !important;
        width: 100% !important;
    }

    /* Input field styling */
    .stTextInput>div>div>input, .stNumberInput>div>div>input {
        border-radius: 8px !important;
        padding: 12px !important;
        font-size: 20px !important;
    }

    /* Header text styling */
    .header {
        text-align: center;
        font-size: 30px;
        font-weight: bold;
        color: green;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# --- HEADER ---
st.markdown("<h1 class='header'>🌾 Smart Farming Dashboard</h1>", unsafe_allow_html=True)
st.markdown("### 🌱 Optimize Your Farming with AI-Powered Insights")

# Load trained models
crop_model = joblib.load("crop_model.pkl")
yield_model = joblib.load("yield_model.pkl")
price_model = joblib.load("price_model.pkl")

# Load preprocessing encoders & scalers
district_encoder = joblib.load("district_encoder.pkl")
crop_encoder = joblib.load("crop_encoder.pkl")
scaler_crop = joblib.load("scaler_crop.pkl")
scaler_yield = joblib.load("scaler_yield.pkl")
scaler_price = joblib.load("scaler_price.pkl")

# Database connection function (SQLite)
def connect_db():
    conn = sqlite3.connect("SmartAgriculture.db")
    return conn

# Create table if not exists
def create_table():
    conn = connect_db()
    cursor = conn.cursor()
    cursor.execute('''CREATE TABLE IF NOT EXISTS UserPredictions (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT,
                        nitrogen INTEGER,
                        phosphorus INTEGER,
                        potassium INTEGER,
                        pH REAL,
                        temperature INTEGER,
                        humidity INTEGER,
                        rainfall INTEGER,
                        district TEXT,
                        date_input TEXT,
                        recommended_crop TEXT,
                        crop_yield REAL,
                        market_price REAL
                    )''')
    conn.commit()
    conn.close()

# Fast2SMS API Key (Replace with your own)
FAST2SMS_API_KEY = "7OgcCHGsB0nCsUo6rmCB9cEoqfDmTCzBx5nPO2xuHRfi2yp9E1ipsEpMWzLo"
def send_sms(phone_number, message):
    url = "https://www.fast2sms.com/dev/bulkV2"
    headers = {
        'authorization': FAST2SMS_API_KEY,
        'Content-Type': "application/x-www-form-urlencoded"
    }
    payload = {
        'route': 'q',
        'message': message,
        'language': 'english',
        'flash': 0,
        'numbers': phone_number
    }
    
    try:
        response = requests.post(url, data=payload, headers=headers)
        if response.status_code == 200:
            return True, "SMS sent successfully!"
        else:
            return False, f"Failed to send SMS: {response.text}"
    except Exception as e:
        return False, str(e)

# Weather API Key (Replace with your own)
WEATHER_API_KEY = "9229d08a62cf4de78b150510252403"

# Function to fetch weather data
def fetch_weather_data(location):
    url = f"http://api.weatherapi.com/v1/current.json?key={WEATHER_API_KEY}&q={location}&aqi=no"
    try:
        response = requests.get(url)
        data = response.json()
        temp = data['current']['temp_c']
        humidity = data['current']['humidity']
        rainfall = data.get('current', {}).get('precip_mm', 0)  # Get rainfall, default to 0mm if missing
        return temp, humidity, rainfall
    except:
        return None

# Function to predict crop, yield, and market price
def predict_crop_yield_price(name, N, P, K, pH, temp, humidity, rainfall, district, date):
    # Crop prediction
    crop_input = [[N, P, K, pH, temp, humidity, rainfall]]
    crop_input_scaled = scaler_crop.transform(crop_input)
    predicted_crop_encoded = crop_model.predict(crop_input_scaled)[0]
    crop = crop_encoder.inverse_transform([predicted_crop_encoded])[0]

    # Yield prediction
    yield_input = [[predicted_crop_encoded, N, P, K, pH, temp, humidity, rainfall]]
    yield_input_scaled = scaler_yield.transform(yield_input)
    crop_yield = yield_model.predict(yield_input_scaled)[0]

    # Market price prediction
    price_input = [[predicted_crop_encoded, crop_yield, district_encoded, month, day_of_year]]
    price_input_scaled = scaler_price.transform(price_input)
    price = price_model.predict(price_input_scaled)[0]

    # Store results in the database
    conn = connect_db()
    cursor = conn.cursor()
    sql = """INSERT INTO UserPredictions (name, nitrogen, phosphorus, potassium, pH, temperature, humidity, rainfall,
              district, date_input, recommended_crop, crop_yield, market_price)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"""

    values = (name, N, P, K, pH, temp, humidity, rainfall, district, date, crop, crop_yield, price)
    cursor.execute(sql, values)
    conn.commit()
    cursor.close()
    conn.close()

    return crop, crop_yield, price

# Initialize database
create_table()

# # Streamlit UI
# st.title("🌾 Smart Agriculture System 🌱")

# User login (only name required)
name = st.text_input("Enter Your Name / உங்கள் பெயரை உள்ளிடவும்", key="name")

if name:
    st.success(f"Welcome, {name}! 🌱")

    # User Input Section
    st.header("🌦 Fetch Weather Data")

    location = st.text_input("Enter Location for Weather Data / வானிலை தரவுக்காக இடத்தை உள்ளிடவும்")
    weather_data = fetch_weather_data(location)

    if weather_data:
        temperature, humidity, rainfall = weather_data
        st.success(f"Auto-fetched Weather Data: {temperature}°C, {humidity}%, {rainfall}mm")
    else:
        st.warning("⚠️ Failed to fetch weather data. Enter manually.")
        temperature = st.number_input("Enter Temperature (°C)", min_value=0.0, step=0.1)
        humidity = st.number_input("Enter Humidity (%)", min_value=0.0, step=0.1)
        rainfall = st.number_input("Enter Rainfall (mm)", min_value=0.0, step=0.1, value=0.0)

    st.header("🌱 Enter Soil & Crop Details")
    nitrogen = st.number_input("Enter Nitrogen (N)", min_value=0.0, step=0.1)
    phosphorus = st.number_input("Enter Phosphorus (P)", min_value=0.0, step=0.1)
    potassium = st.number_input("Enter Potassium (K)", min_value=0.0, step=0.1)
    pH = st.number_input("Enter Soil pH", min_value=0.0, step=0.1)

    # Dropdown for district selection
    district = st.selectbox("Select District for Market Price / சந்தை விலைக்கான மாவட்டத்தை தேர்வுசெய்க", district_encoder.classes_)
    district_encoded = district_encoder.transform([district])[0]

    # Date input
    date = st.date_input("Select Date / தேதியை தேர்ந்தெடுக்கவும்")
    month = date.month
    day_of_year = date.timetuple().tm_yday

    if st.button("Predict"):
        crop, crop_yield, price = predict_crop_yield_price(name, nitrogen, phosphorus, potassium, pH, temperature, humidity, rainfall, district, date)
        st.success("✅ Prediction Complete!")
        st.write(f"🌾 *Recommended Crop:* {crop}")
        st.write(f"🌱 *Predicted Yield:* {crop_yield:.2f} kg/ha")
        st.write(f"💰 *Predicted Market Price:* ₹{price:.2f}INR/ha")

     # *Thank You Message*
        st.markdown("### 🌿 Thank you for using the Smart Agriculture System! 🚜")
 
        # Store the prediction result in session state
        st.session_state["crop"] = crop
        st.session_state["crop_yield"] = crop_yield
        st.session_state["price"] = price
        st.session_state["prediction_done"] = True

    # Optional: Enter phone number to receive SMS
    if st.session_state.get("prediction_done"):
        phone = st.text_input("📲 Enter your phone number to receive SMS notification:")

        if st.button("Send SMS"):
            crop = st.session_state.get("crop")
            crop_yield = st.session_state.get("crop_yield")
            price = st.session_state.get("price")
        
            if name and crop and crop_yield and price and phone:
                sms_message = f"welcome🥰,{name}\n Recommended Crop: {crop}\n Yield: {crop_yield:.2f} kg/ha\n Price: ₹{price:.2f}/ha"
                sent, msg = send_sms(phone, sms_message)
                if sent:
                    st.success("✅ SMS sent successfully!")
                else:
                    st.error(f"❌ {msg}")

        else:
            st.warning("⚠️ Please make sure all details are available and phone is entered.")

